### DISCUSSION TITLE
I18n, Tilt & Encoding Errors, Oh My!

### DISCUSSION THREAD

**Discussion by activestylus** [jeremyevans/roda#353] [General]
I'm running into an encoding error which is preventing the deployment of my Roda app. A real head scratcher this one is. Not sure if its a problem with Roda, the render plugin, Tilt or Slim gem. Curious if anyone can help me solve it.

```
#<Encoding::InvalidByteSequenceError: /user/app/releases/4/views/home.slim is not valid US-ASCII>
/user/app/vendor/bundle/ruby/2.6.0/gems/tilt-2.0.11/lib/tilt/template.rb:95:in `initialize'
/user/app/vendor/bundle/ruby/2.6.0/gems/tilt-2.0.11/lib/tilt/mapping.rb:138:in `new'
/user/app/vendor/bundle/ruby/2.6.0/gems/tilt-2.0.11/lib/tilt/mapping.rb:138:in `new'
/user/app/vendor/bundle/ruby/2.6.0/gems/tilt-2.0.11/lib/tilt.rb:43:in `new'
/user/app/vendor/bundle/ruby/2.6.0/gems/roda-3.26.0/lib/roda/plugins/render.rb:584:in `block in retrieve_template'
/user/app/vendor/bundle/ruby/2.6.0/gems/roda-3.26.0/lib/roda/plugins/render.rb:486:in `cached_template'
/user/app/vendor/bundle/ruby/2.6.0/gems/roda-3.26.0/lib/roda/plugins/render.rb:559:in `retrieve_template'
/user/app/vendor/bundle/ruby/2.6.0/gems/roda-3.26.0/lib/roda/plugins/render.rb:348:in `render'
/user/app/vendor/bundle/ruby/2.6.0/gems/roda-3.26.0/lib/roda/plugins/render.rb:378:in `view'
/home/kryptonite/www/ola/releases/4/app.rb:21:in `block (2 levels) in <class:App>'
/user/app/vendor/bundle/ruby/2.6.0/gems/roda-3.26.0/lib/roda.rb:1116:in `always'
/user/app/vendor/bundle/ruby/2.6.0/gems/roda-3.26.0/lib/roda.rb:955:in `root'
/home/kryptonite/www/ola/releases/4/app.rb:18:in `block in <class:App>'
/user/app/vendor/bundle/ruby/2.6.0/gems/roda-3.26.0/lib/roda.rb:557:in `block in _roda_handle_main_route'
/user/app/vendor/bundle/ruby/2.6.0/gems/roda-3.26.0/lib/roda.rb:555:in `catch'
/user/app/vendor/bundle/ruby/2.6.0/gems/roda-3.26.0/lib/roda.rb:555:in `_roda_handle_main_route'
/user/app/vendor/bundle/ruby/2.6.0/gems/roda-3.26.0/lib/roda/plugins/error_handler.rb:87:in `_roda_handle_main_route'
/user/app/vendor/bundle/ruby/2.6.0/gems/roda-3.26.0/lib/roda/plugins/direct_call.rb:18:in `call'
/user/app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
/user/app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
/user/app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
/user/app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
/user/app/vendor/bundle/ruby/2.6.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

I've done the following to view the encoding for all related files, including layouts, partial, translation file and everything appears to be in order:

```bash
$ file -I views/home.slim 
views/home.slim: text/plain; charset=utf-8

$ file -I views/layout.slim 
views/layout.slim: text/plain; charset=utf-8

$ file -I views/_menu.slim 
views/_menu.slim: text/plain; charset=utf-8

$ file -I I18n/gl.yml
I18n/gl.yml: text/plain; charset=utf-8
```
Here is the top portion of my App file:
```ruby
require "roda"
require 'slim'
require_relative "lib/helpers"
Slim::Engine.options[:encoding]= 'utf-8'

class App < Roda
  plugin :i18n, :locale => ['gl','es','en']
  plugin :render, engine: 'slim', views: 'views', layout: 'layout'
  plugin :partials
  plugin :content_for
  plugin :public

  route do |r|
    ...
  end
end
```
Here's my translation file:
```yaml
lang: gl
home_title: 'Xestión Turística en Ribeira Sacra, do Rio Miño'
home_description: 'Xestión Turística'
tourism_management: 'Xestión Turística'
in_ribeira: 'en Ribeira Sacra'
where_we_are: 'Donde Estamos'
from: desde
features:
  - 'Xestión do Rexistro e Licenzas'
  - 'Gestion de Limpeza e Mantemento'
  - 'Imaxe Corporativa / Social Marketing'
  - 'Entrega de Chaves'
amen:
  river: Vistas Rio
  fire: Chimenea
  park: Parking
  wifi: Wifi
  wash: Lava/Secadora
bed_1: cama
bed_n: camas
room_1: habitación
room_n: habitaciones
bath_1: baño
bath_n: baños
sofabed_1: sofa cama
sofabed_n: sofa camas
night: noite
h1_404: "404: No Encontrado"
p1_404: Esta páxina no existe
p2_404: Comproba el enlace o
a_404: Ir al Inicio
back_home: Volver al Inicio
```
Some details on my environment:
```
Linux 4.15.0-52-generic x86_64
ruby -v 2.6.3 (installed and running via RVM)
rubygems -v 3.0.3
bundler -v 2.0.2
GEM
  remote: https://rubygems.org/
  specs:
    active_hash (3.1.1)
      activesupport (>= 5.0.0)
    activesupport (6.1.7)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    better_errors (2.10.0)
      erubi (>= 1.0.0)
      rack (>= 0.9.0)
      rouge (>= 1.0.0)
    binding_of_caller (1.0.0)
      debug_inspector (>= 0.0.1)
    concurrent-ruby (1.1.10)
    debug_inspector (1.1.0)
    erubi (1.12.0)
    ffi (1.16.3)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    minitest (5.16.3)
    puma (3.12.6)
    r18n-core (3.2.0)
    rack (2.2.4)
    roda (3.26.0)
      rack
    roda-i18n (0.4.0)
      r18n-core (~> 3.0)
      roda (~> 3.7)
      tilt
    rouge (3.30.0)
    sassc (2.4.0)
      ffi (~> 1.9)
    slim (4.1.0)
      temple (>= 0.7.6, < 0.9)
      tilt (>= 2.0.6, < 2.1)
    temple (0.8.2)
    tilt (2.0.11)
    tzinfo (2.0.5)
      concurrent-ruby (~> 1.0)
    zeitwerk (2.6.1)
```

Any ideas?
