### ISSUE TITLE
[Assets Plugin] Accept string options

### ISSUE THREAD

**Issue by badosu** [jeremyevans/roda#43]
This is an example of how the assets plugin is loaded in my application, it's a fairly small project yet:

``` ruby
# site
class Site < Roda
  #
  plugin :assets, group_subdirs: false,
         css: { site: %w[application.css.sass] },
         js:  { site: %w[lib/jquery-2.1.3.js lib/chosen.jquery.js lib/jquery.mask.js bootstrap/bootstrap.min.js lib/bootstrap-slider.js home.js rent_registration.js] },
         dependencies: { 'assets/css/application.css.sass' => ['assets/css/**/*.sass' 'assets/css/**/*.scss'] }
  #
end
```

Notice how this is not scalable and pollutes the main file for the Roda application. To fix this I implemented the following structure:

``` ruby
class Site < Roda
  #
  plugin :assets, YAML.load_file('assets/manifest.yml')
  #
end
```

``` yaml
---
# assets/manifest.yml

css:
  site:
    - application.css.sass

js:
  site: 
    - lib/jquery-2.1.3.js
    - lib/chosen.jquery.js
    - lib/jquery.mask.js
    - lib/bootstrap.js
    - lib/bootstrap-slider.js
    - home.js
    - rent_registration.js

dependencies:
  assets/css/application.css.sass:
    - assets/css/**/*.sass
    - assets/css/**/*.scss

group_subdirs: false
```

This is much more elegant and organized.

The only problem is that the assets plugin expects symbols as arguments whereas the keys of YAML dictionaries are loaded as strings.

I am filing up this issue to ask whether it is feasible to implement this or not considering the plugin structure and if it's desirable. If so, I can send the PR myself.

I am using the `Hash#deep_symbolize_keys` extension that comes with `I18n` to workaround this.
